# Copyright 2020 Canonical
# See LICENSE file for licensing details.

options:
  influxdb-host:
    default: ""
    description: The hostname of the remote influxdb to submit metrics to
    type: string
